sudo: false
language: python
python:
    - '2.7'
    - '3.4'
    - '3.3'
    - '3.5'

git:
    depth: 150

branches:
    only:
        - master

install:
    - 'pip install -r requirements.txt'
    - 'pip install nose coverage codecov'
script:
    - nosetests tests --with-coverage -v
after_success:
    - codecov
